<?php

return array(
    'name' => 'Flute',
    'description' => 'Flute - is modern and powerful engine for creating websites for game servers.',
    'keywords' => 'Flute, game servers, gaming',
    'url' => '',
    'flute_market_url' => 'https://flute-cms.com',
    'debug' => false,
    'cron_mode' => false,
    'auto_update' => false,
    'footer_additional' => null,
    'create_backup' => true,
    'backup_vendor_on_composer' => true,
    'maintenance_mode' => false,
    'steam_api' => '',
    'change_theme' => true,
    'default_theme' => 'dark',
    'debug_ips' =>
        array(
        ),
    'development_mode' => false,
    'logo' => 'assets/img/logo.svg',
    'key' => '',
    'tips' => true,
    'timezone' => 'Europe/Moscow',
    'is_performance' => false,
    'share' => true,
    'flute_copyright' => true,
    'copyright' => '',
    'discord_link_roles' => false,
    'bg_image' => '',
    'bg_image_light' => '',
    'maintenance_message' => '',
    'footer_description' => '',
    'csrf_enabled' => true,
    'convert_to_webp' => true,
    'flute_key' => '',
    'robots' => 'index, follow',
    'logo_light' => 'assets/img/logo-light.svg',
    'trusted_proxies' => [
        'REMOTE_ADDR',
    ],
    'trusted_hosts' => [
    ],
    'auth_enabled' => true,
    'profile_enabled' => true,
    'balance_enabled' => true,
    'notifications_enabled' => true,
    'notifications_popup_enabled' => true,
    'notifications_sound_enabled' => true,
    'session' =>
        array(
            'name' => 'flute_session',
            'secure' => 'auto',
            'http_only' => true,
            'same_site' => 'Lax',
            'domain' => NULL,
            'path' => '/',
            'lifetime' => 0,
        ),
);
