<?php

return array (
  'name' => 'Flute',
  'description' => 'Flute - is modern and powerful engine for creating websites for game servers.',
  'keywords' => 'Flute, game servers, gaming',
  'url' => '',
  'flute_market_url' => 'https://flute-cms.com',
  'debug' => false,
  'cron_mode' => false,
  'footer_additional' => null,
  'create_backup' => true,
  'maintenance_mode' => false,
  'steam_api' => '',
  'change_theme' => true,
  'default_theme' => 'dark',
  'debug_ips' => 
  array (
  ),
  'development_mode' => false,
  'logo' => 'assets/img/logo.svg',
  'key' => '',
  'tips' => true,
  'timezone' => 'Europe/Moscow',
  'is_performance' => false,
  'share' => true,
  'flute_copyright' => true,
  'discord_link_roles' => false,
  'bg_image' => '',
  'bg_image_light' => '',
  'maintenance_message' => '',
  'footer_description' => '',
  'csrf_enabled' => true,
  'convert_to_webp' => true,
  'flute_key' => '',
  'robots' => 'index, follow',
  'logo_light' => 'assets/img/logo-light.svg',
);
