name: Legacy Build Support (Deprecated)

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build from current branch'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  legacy-build:
    runs-on: ubuntu-latest
    if: github.event.inputs.force_build == 'true'

    steps:
      - name: Deprecation Notice
        run: |
          echo "⚠️  This workflow is deprecated!"
          echo "Please use the new promotion workflow instead:"
          echo "Actions → Promote to Main → Run workflow"
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev --no-progress --optimize-autoloader

      - name: Create manual build
        run: |
          BUILD_DATE=$(date +"%Y%m%d_%H%M%S")
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ARCHIVE_NAME="flute-cms-manual-${BRANCH_NAME}-${BUILD_DATE}.zip"
          
          zip -r "$ARCHIVE_NAME" . \
            -x "*.git*" \
            -x "*.github*" \
            -x "tests/*" \
            -x "*.md"
            
          echo "Manual build created: $ARCHIVE_NAME"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: manual-build
          path: ${{ env.ARCHIVE_NAME }}
          retention-days: 7
