name: Static Analysis (PHPStan)

on:
  pull_request:
    paths: ["**.php"]
  push:
    branches: [early, main]
    paths: ["**.php"]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.3']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PHPStan temporarily disabled
        run: echo "PHPStan is temporarily disabled and will not run in CI."
